; quepaxa-read-failover.scm — repro for the k3s E2 wedge: linearizable reads
; cluster-wide never complete after a coordinator SIGKILL + restart under churn.
;   crabscheme run test/quepaxa-read-failover.scm
(include "test/harness.scm")
(include "src/quepaxa.scm")

(define (test-apply sm cmd) (append sm (list cmd)))
(define (qcl-make ids opts)
  (map (lambda (id) (cons id (make-qp id ids test-apply '() opts))) ids))
(define (qcl-get c id) (cdr (assv id c)))
(define (qcl-set c id st)
  (cond ((null? c) (list (cons id st)))
        ((eqv? (caar c) id) (cons (cons id st) (cdr c)))
        (else (cons (car c) (qcl-set (cdr c) id st)))))
(define (qsettle c queue blocked)
  (if (null? queue) c
      (let* ((m (car queue)) (from (car m)) (to (cadr m)) (msg (caddr m)))
        (if (or (memv from blocked) (memv to blocked))
            (qsettle c (cdr queue) blocked)
            (let* ((r (qp-step (qcl-get c to) from msg))
                   (c2 (qcl-set c to (car r)))
                   (more (map (lambda (o) (list to (car o) (cdr o))) (cdr r))))
              (qsettle c2 (append (cdr queue) more) blocked))))))
(define (qdrive c id action blocked)
  (let* ((r (action (qcl-get c id)))
         (c2 (qcl-set c id (car r))))
    (qsettle c2 (map (lambda (o) (list id (car o) (cdr o))) (cdr r)) blocked)))
(define (qtick-all c blocked)
  (let loop ((ids (map car c)) (c c) (q '()))
    (if (null? ids)
        (qsettle c q blocked)
        (if (memv (car ids) blocked)
            (loop (cdr ids) c q)
            (let ((r (qp-tick (qcl-get c (car ids)))))
              (loop (cdr ids)
                    (qcl-set c (car ids) (car r))
                    (append q (map (lambda (o) (list (car ids) (car o) (cdr o))) (cdr r)))))))))
; drain done-reads, RETURNING (tags . c') so the drained state is kept
(define (drain-reads c id)
  (let ((r (qp-take-reads (qcl-get c id))))
    (cons (car r) (qcl-set c id (cdr r)))))

; ============================================================
(section "reads issued WHILE coordinator dead complete after hedge (all nodes)")
(let* ((c (qcl-make '(1 2 3 4 5) '((hedge . 2))))
       (dead '(1))
       ; churn: writes from several nodes while coordinator is dead
       (c (qdrive c 2 (lambda (st) (qp-propose st 'w2)) dead))
       (c (qdrive c 3 (lambda (st) (qp-propose st 'w3)) dead))
       ; reads from every surviving node while coordinator dead
       (c (qdrive c 2 (lambda (st) (qp-read st 'r2)) dead))
       (c (qdrive c 3 (lambda (st) (qp-read st 'r3)) dead))
       (c (qdrive c 4 (lambda (st) (qp-read st 'r4)) dead))
       (c (qdrive c 5 (lambda (st) (qp-read st 'r5)) dead))
       ; hedge fires
       (c (qtick-all c dead)) (c (qtick-all c dead))
       (c (qtick-all c dead)) (c (qtick-all c dead))
       (c (qtick-all c dead)) (c (qtick-all c dead)))
  (let* ((d2 (drain-reads c 2)) (c (cdr d2))
         (d3 (drain-reads c 3)) (c (cdr d3))
         (d4 (drain-reads c 4)) (c (cdr d4))
         (d5 (drain-reads c 5)) (c (cdr d5)))
  (check "r2 completed" '(r2) (car d2))
  (check "r3 completed" '(r3) (car d3))
  (check "r4 completed" '(r4) (car d4))
  (check "r5 completed" '(r5) (car d5))
  ; coordinator restarts (fresh engine, bumped boot, snapshot-installed to n2's applied)
  (let* ((p (qp-applied (qcl-get c 2)))
         (sm (qp-take-n (qp-sm (qcl-get c 2)) p))
         (n1 (qp-install-snapshot (make-qp 1 '(1 2 3 4 5) test-apply '() '((hedge . 2) (boot . 1))) p sm '()))
         (c (qcl-set c 1 n1))
         (c (qtick-all c '())) (c (qtick-all c '())) (c (qtick-all c '()))
         ; post-restart: reads from every node must complete
         (c (qdrive c 1 (lambda (st) (qp-read st 'p1)) '()))
         (c (qdrive c 2 (lambda (st) (qp-read st 'p2)) '()))
         (c (qdrive c 4 (lambda (st) (qp-read st 'p4)) '()))
         (c (qtick-all c '())) (c (qtick-all c '())) (c (qtick-all c '()))
         (c (qtick-all c '())))
    (check "post-restart read via restarted coordinator" '(p1) (car (drain-reads c 1)))
    (check "post-restart read via n2" '(p2) (car (drain-reads c 2)))
    (check "post-restart read via n4" '(p4) (car (drain-reads c 4)))
    (check "writes survived" #t (and (memv 'w2 (qp-sm (qcl-get c 2)))
                                     (memv 'w3 (qp-sm (qcl-get c 2))) #t)))))

; ============================================================
(section "read pfwd'd to coordinator that dies BEFORE proposing — hedge rescues")
(let* ((c (qcl-make '(1 2 3 4 5) '((hedge . 3))))
       ; n2 issues a read; pfwd reaches NOBODY (n1 dies with it in its mailbox)
       (c (qdrive c 2 (lambda (st) (qp-read st 'lost)) '(1)))
       ; churn from others fills slots meanwhile
       (c (qdrive c 3 (lambda (st) (qp-propose st 'x1)) '(1)))
       (c (qdrive c 4 (lambda (st) (qp-propose st 'x2)) '(1)))
       (c (qtick-all c '(1))) (c (qtick-all c '(1)))
       (c (qtick-all c '(1))) (c (qtick-all c '(1)))
       (c (qtick-all c '(1))))
  (check "read hedge-rescued despite dead coordinator + churn" '(lost) (car (drain-reads c 2))))

(done!)
